### ISSUE TITLE
Not Found Response

### ISSUE THREAD

**Issue by iambudi** [furrary/livereload#7]
Hi,

I use livereload on angulardart 5.
```bash
pub run livereload --spa on
[INFO] Serving a WebSocket server at ws://localhost:4242
[INFO] Entrypoint: Generating build script...
[INFO] Entrypoint: Generating build script completed, took 324ms
...
[INFO] Build: Succeeded after 215ms with 0 outputs

[INFO] `build_runner` starts serving `on` on port 8080
Browse your web app at http://localhost:8000
```
Accessing localhost:8000 return 404.

When i run with `pub run build_runner serve` it displays page normally.

**Comment by furrary** [comment]
From the log:

```
[INFO] `build_runner` starts serving `on` on port 8080
```

It started serving the directory `on` instead of `web` . 

I'm sorry, the document is not clear enough.

To enable SPA, you don't need to specify the option because it's the default. If you want to disable it, here's the way.

```
pub run livereload --no-spa
```
